In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [14]:
l = [1, 2, 3]
l


[1, 2, 3]

In [8]:
python_list = list(range(100))
python_list[:5]

[0, 1, 2, 3, 4]

In [10]:
import sys

sys.getsizeof(python_list[0])*len(python_list)

2800

In [11]:
numpy_array = np.arange(100)
numpy_array[:5]

array([0, 1, 2, 3, 4])

In [13]:
numpy_array.nbytes

800

In [16]:
l1=[1,2,3]
l2=[8,7,9]

for x, y in zip(l1,l2):
    print(x,y)


1 8
2 7
3 9


In [18]:
import time

SIZE = 1000000

l1= list(range(SIZE))
l2 = list(range(SIZE))

start_time = time.time()
l3 = [x+y for x,y in zip(l1,l2)]
end_time = time.time()
print("Time taken for list addition:", end_time - start_time)

Time taken for list addition: 0.02490091323852539


In [19]:
n1 = np.arange(SIZE)
n2 = np.arange(SIZE)
n1[:4], n2[:4]

(array([0, 1, 2, 3]), array([0, 1, 2, 3]))

In [20]:
start_time = time.time()
n3 = n1 + n2
end_time = time.time()
print("Time taken for numpy array addition:", end_time - start_time)

Time taken for numpy array addition: 0.0030739307403564453


## Basic Operations

In [1]:
import numpy as np

In [2]:
rev_q1 = np.array([10,12,9])
rev_q1.ndim

1

In [3]:
rev = np.array([[10,12,9],[8,7,9]])
rev.ndim

2

In [4]:
rev

array([[10, 12,  9],
       [ 8,  7,  9]])

In [5]:
rev[1,0]

8

In [7]:
rev[1,0] = 10
rev

array([[10, 12,  9],
       [10,  7,  9]])

In [8]:
rev.dtype

dtype('int64')

In [9]:
rev.itemsize

8

In [10]:
rev.size


6

In [11]:
rev.shape

(2, 3)

In [13]:
np.sort(rev, axis=None)

array([ 7,  9,  9, 10, 10, 12])

In [14]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
np.arange(20,30,2)

array([20, 22, 24, 26, 28])

In [18]:
np.linspace(10,20,20)

array([10.        , 10.52631579, 11.05263158, 11.57894737, 12.10526316,
       12.63157895, 13.15789474, 13.68421053, 14.21052632, 14.73684211,
       15.26315789, 15.78947368, 16.31578947, 16.84210526, 17.36842105,
       17.89473684, 18.42105263, 18.94736842, 19.47368421, 20.        ])

In [19]:
rev.ravel()

array([10, 12,  9, 10,  7,  9])

In [20]:
rev.flatten()

array([10, 12,  9, 10,  7,  9])

In [21]:
rev.reshape(3,2)

array([[10, 12],
       [ 9, 10],
       [ 7,  9]])

In [22]:
rev.reshape(6,1)

array([[10],
       [12],
       [ 9],
       [10],
       [ 7],
       [ 9]])

In [23]:
rev.min()

7

In [24]:
rev.max()

12

In [25]:
rev.sum(axis=1)

array([31, 26])

In [26]:
rev.sum(axis=0)

array([20, 19, 18])

In [27]:
rev 


array([[10, 12,  9],
       [10,  7,  9]])

In [28]:
for row in rev:
    print(row)

[10 12  9]
[10  7  9]


In [29]:
b =np.array([1,4,16])

In [30]:
np.std(b)

6.48074069840786

## Matrix operations

In [31]:
import numpy as np

In [33]:
q1 = np.array([
    [200, 220, 250],
    [150, 180, 210],
    [300, 330, 360]
])

q2 = np.array([
    [209, 231, 259],
    [155, 192, 222],
    [310, 340, 375]
])

In [34]:
q1 + q2

array([[409, 451, 509],
       [305, 372, 432],
       [610, 670, 735]])

In [35]:
q2 - q1

array([[ 9, 11,  9],
       [ 5, 12, 12],
       [10, 10, 15]])

In [37]:
(q2-q1)*100/q1

array([[4.5       , 5.        , 3.6       ],
       [3.33333333, 6.66666667, 5.71428571],
       [3.33333333, 3.03030303, 4.16666667]])

In [38]:
prices = np.array([
    [10, 12, 11],
    [8, 9, 10],
    [15, 16, 17]
])

q1_revenue = q1 * prices
q1_revenue

array([[2000, 2640, 2750],
       [1200, 1620, 2100],
       [4500, 5280, 6120]])

In [43]:
q1_discounts = q1_revenue*0.2
q1_discounts

array([[ 400.,  528.,  550.],
       [ 240.,  324.,  420.],
       [ 900., 1056., 1224.]])

In [44]:
net_revenue = q1_revenue - (q1_discounts)

In [45]:
net_revenue

array([[1600., 2112., 2200.],
       [ 960., 1296., 1680.],
       [3600., 4224., 4896.]])

In [46]:
np.sum(net_revenue)

22568.0

In [47]:
features = np.array([
    [2000, 3],
    [1800, 2]
])

weights = np.array([150, 50000])
np.dot(features, weights)
    

array([450000, 370000])

In [48]:
c = np.array([1,2,3])
d = np.array([4,5,6])   

np.cross(c,d)

array([-3,  6, -3])

## Slicing and Stacking

In [49]:
import numpy as np

In [50]:
a = np.array([6,7,8,9])

In [51]:
a[0:2]

array([6, 7])

In [52]:
a[2:]

array([8, 9])

In [53]:
a[-1]

9

In [54]:
a[-2:]

array([8, 9])

In [56]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
b[1,2]

6

In [66]:
b[2,0]

7

In [67]:
b[-1]

array([7, 8, 9])

In [68]:
b[-1,0:2]

array([7, 8])

In [70]:
b[:,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [72]:
# Customer ID
c = np.array([
    [101, 'Mira'],
    [102, 'Ravi'],
    [103, 'Abdul']
])
#Customer ID, Purchase Amount, Purchase Date
d = np.array([
    [101, 250.50, '2023-08-01'],
    [102, 150.00, '2023-08-02'],
    [103, 300.75, '2023-08-01']
])

In [74]:
# We will use horizontal stacking to combine the two arrays based on the customer ID. However, since the customer names are strings and the purchase amounts are floats, we need to ensure that the data types are compatible. We can convert the purchase amounts to strings for this purpose.
np.hstack((c,d))

array([['101', 'Mira', '101', '250.5', '2023-08-01'],
       ['102', 'Ravi', '102', '150.0', '2023-08-02'],
       ['103', 'Abdul', '103', '300.75', '2023-08-01']], dtype='<U32')

In [75]:
c

array([['101', 'Mira'],
       ['102', 'Ravi'],
       ['103', 'Abdul']], dtype='<U21')

In [76]:
e= np.array([
    ['104', ' Venkat'],
    ['105', ' Priya'],
    ['106', ' Arjun']
])
e


array([['104', ' Venkat'],
       ['105', ' Priya'],
       ['106', ' Arjun']], dtype='<U7')

In [77]:
np.stack((c,e))

array([[['101', 'Mira'],
        ['102', 'Ravi'],
        ['103', 'Abdul']],

       [['104', ' Venkat'],
        ['105', ' Priya'],
        ['106', ' Arjun']]], dtype='<U21')

In [78]:
transactions = np.array([
    [101, 'Mira', 250.50, '2023-08-01'],
    [102, 'Ravi', 150.00, '2023-08-02'],
    [103, 'Abdul', 300.75, '2023-08-01'],
    [104, 'Venkat', 200.00, '2023-08-03'],
    [105, 'Priya', 180.25, '2023-08-02'],
    [106, 'Arjun', 220.50, '2023-08-03']
])

In [79]:
transactions

array([['101', 'Mira', '250.5', '2023-08-01'],
       ['102', 'Ravi', '150.0', '2023-08-02'],
       ['103', 'Abdul', '300.75', '2023-08-01'],
       ['104', 'Venkat', '200.0', '2023-08-03'],
       ['105', 'Priya', '180.25', '2023-08-02'],
       ['106', 'Arjun', '220.5', '2023-08-03']], dtype='<U32')

In [80]:
np.hsplit(transactions, [3])

[array([['101', 'Mira', '250.5'],
        ['102', 'Ravi', '150.0'],
        ['103', 'Abdul', '300.75'],
        ['104', 'Venkat', '200.0'],
        ['105', 'Priya', '180.25'],
        ['106', 'Arjun', '220.5']], dtype='<U32'),
 array([['2023-08-01'],
        ['2023-08-02'],
        ['2023-08-01'],
        ['2023-08-03'],
        ['2023-08-02'],
        ['2023-08-03']], dtype='<U32')]

In [81]:
np.hsplit(transactions, [2])

[array([['101', 'Mira'],
        ['102', 'Ravi'],
        ['103', 'Abdul'],
        ['104', 'Venkat'],
        ['105', 'Priya'],
        ['106', 'Arjun']], dtype='<U32'),
 array([['250.5', '2023-08-01'],
        ['150.0', '2023-08-02'],
        ['300.75', '2023-08-01'],
        ['200.0', '2023-08-03'],
        ['180.25', '2023-08-02'],
        ['220.5', '2023-08-03']], dtype='<U32')]

In [82]:
np.vsplit(transactions, [4])

[array([['101', 'Mira', '250.5', '2023-08-01'],
        ['102', 'Ravi', '150.0', '2023-08-02'],
        ['103', 'Abdul', '300.75', '2023-08-01'],
        ['104', 'Venkat', '200.0', '2023-08-03']], dtype='<U32'),
 array([['105', 'Priya', '180.25', '2023-08-02'],
        ['106', 'Arjun', '220.5', '2023-08-03']], dtype='<U32')]

In [83]:
x, y = np.vsplit(transactions, [4])

In [84]:
x

array([['101', 'Mira', '250.5', '2023-08-01'],
       ['102', 'Ravi', '150.0', '2023-08-02'],
       ['103', 'Abdul', '300.75', '2023-08-01'],
       ['104', 'Venkat', '200.0', '2023-08-03']], dtype='<U32')

In [85]:
y

array([['105', 'Priya', '180.25', '2023-08-02'],
       ['106', 'Arjun', '220.5', '2023-08-03']], dtype='<U32')

In [86]:
monthly_sales = np.array([30,33,34,28,42])

result = monthly_sales <32
result

array([ True, False, False,  True, False])

In [87]:
monthly_sales[result]

array([30, 28])

In [88]:
monthly_sales.max()

42

In [90]:
index = np.argmax(monthly_sales)

In [91]:
monthly_sales[index]

42

In [92]:
transactions

array([['101', 'Mira', '250.5', '2023-08-01'],
       ['102', 'Ravi', '150.0', '2023-08-02'],
       ['103', 'Abdul', '300.75', '2023-08-01'],
       ['104', 'Venkat', '200.0', '2023-08-03'],
       ['105', 'Priya', '180.25', '2023-08-02'],
       ['106', 'Arjun', '220.5', '2023-08-03']], dtype='<U32')

In [94]:
transactions[:,2]

array(['250.5', '150.0', '300.75', '200.0', '180.25', '220.5'],
      dtype='<U32')

In [95]:
t_index = np.argmax(transactions[:,2].astype(float))
t_index

2

In [96]:
transactions[t_index]

array(['103', 'Abdul', '300.75', '2023-08-01'], dtype='<U32')