At **AtliQ**, a software service company, the **HR team** wants to understand how happy employees are with company policies and how long they've been with the company. This survey aims to help HR improve the work environment and keep employees satisfied.

**Data Structure:** Two numpy arrays capture survey results and employee details:

**Employee Details:** Contains Employee ID, Department, and Number of Years with AtliQ.

**Survey Results:** Contains Employee ID and Happiness Score (scaled 1-10).

In [1]:
import numpy as np

# Employee Details: Employee ID, Department, Number of Years with AtliQ
employee_details = np.array([
    [101, 'Sales', 3],  
    [102, 'HR', 5],    
    [103, 'IT', 2],        
    [104, 'Sales', 8],    
    [105, 'IT', 6],      
    [106, 'HR', 4],           
    [107, 'IT', 7],    
    [108, 'Sales', 1], 
    [109, 'HR', 3]          
])

# Survey Results: Employee ID, Happiness Score (1-10)
survey_results = np.array([
    [101, 8],
    [102, 10],
    [103, 9],
    [104, 6],
    [105, 7],
    [106, 8],
    [107, 9],
    [108, 5],
    [109, 7]
])


### Task 1: Merge Arrays

**Scenario:** To streamline analysis, combine the employee details with their survey results.

**Action:** Use ```np.hstack``` to horizontally stack the two arrays.

In [8]:
# write code here()
merge = np.hstack((employee_details, survey_results))
merge

array([['101', 'Sales', '3', '101', '8'],
       ['102', 'HR', '5', '102', '10'],
       ['103', 'IT', '2', '103', '9'],
       ['104', 'Sales', '8', '104', '6'],
       ['105', 'IT', '6', '105', '7'],
       ['106', 'HR', '4', '106', '8'],
       ['107', 'IT', '7', '107', '9'],
       ['108', 'Sales', '1', '108', '5'],
       ['109', 'HR', '3', '109', '7']], dtype='<U21')

### Task 2: Print Scores

**Scenario:** HR wants a quick view of all happiness scores to gauge overall employee sentiment.

**Action:** Display all happiness scores from the merged array.

In [9]:
# write code here
merge[:,4]


array(['8', '10', '9', '6', '7', '8', '9', '5', '7'], dtype='<U21')

### Task 3: Sort Scores

**Scenario:** HR needs to identify the range of happiness scores to plan specific interventions.

**Action:** Sort and print the happiness scores in ascending order.

In [15]:
# write code here
np.sort(merge[:,4].astype(int))

array([ 5,  6,  7,  7,  8,  8,  9,  9, 10])

### Task 4: Employee Details

**Scenario:** For a meeting, HR needs a list of employees' IDs and departments without other details.

**Action:** Iterate through the array and print each employee's ID and department.

In [16]:
# write code here
for row in merge:
    print(f'ID: {row[0]}, Department: {row[1]}')

ID: 101, Department: Sales
ID: 102, Department: HR
ID: 103, Department: IT
ID: 104, Department: Sales
ID: 105, Department: IT
ID: 106, Department: HR
ID: 107, Department: IT
ID: 108, Department: Sales
ID: 109, Department: HR


### Task 5: Happiness Scores

**Scenario:** HR wants to review individual happiness scores to follow up with specific departments or employees.

**Action:** Print the happiness score alongside each employee ID from the merged array.

In [18]:
# write code here
for row in merge:
    print(f'ID: {row[0]}, Happiness score: {row[4]}')

ID: 101, Happiness score: 8
ID: 102, Happiness score: 10
ID: 103, Happiness score: 9
ID: 104, Happiness score: 6
ID: 105, Happiness score: 7
ID: 106, Happiness score: 8
ID: 107, Happiness score: 9
ID: 108, Happiness score: 5
ID: 109, Happiness score: 7


### Task 6: Convert Scores

**Scenario:** For statistical analysis, the HR team needs the happiness scores in a consistent format.

**Action:** Convert the happiness scores to float type using ```astype(float)```.

In [20]:
# write code here
merge[:,4].astype(float)

array([ 8., 10.,  9.,  6.,  7.,  8.,  9.,  5.,  7.])

### Task 7: Average Score

**Scenario:** To measure the effectiveness of current policies, HR needs the average happiness score.

**Action:** Calculate and print the average happiness score of all employees.

In [21]:
# write code here
np.mean(merge[:,4].astype(float))

7.666666666666667

In [30]:
np.average(merge[:,4].astype(float))

7.666666666666667

### Task 8: Unique Departments

**Scenario:** HR is reviewing which departments are represented in the survey to ensure all are included in future plans.

**Action:** Use ```np.unique``` to find and print all unique departments from the employee details.

In [25]:
# first print departments from all the records

merge[:,1]




array(['Sales', 'HR', 'IT', 'Sales', 'IT', 'HR', 'IT', 'Sales', 'HR'],
      dtype='<U21')

In [26]:
# now print unique departments

# write code here

np.unique(merge[:,1])

array(['HR', 'IT', 'Sales'], dtype='<U21')

### Task 9: HR Happiness

**Scenario:** HR is conducting a self-assessment to understand how their own department perceives company policies.

**Action:** Calculate and print the average happiness score within the HR department.

In [27]:
# First print all the records in HR department

# write code here
merge[merge[:,1] == 'HR']

array([['102', 'HR', '5', '102', '10'],
       ['106', 'HR', '4', '106', '8'],
       ['109', 'HR', '3', '109', '7']], dtype='<U21')

In [28]:
# Now from these records only print  the happiness score column. Convert that to float using astype(float) function

# write code here
merge[merge[:,1]=='HR'][:,4].astype(float)

array([10.,  8.,  7.])

In [29]:
# Take an average of this column using np.mean() function

# write code here
np.average(merge[merge[:,1]=='HR'][:,4].astype(float))

8.333333333333334